### ISSUE TITLE
add ajroach42.com

### ISSUE THREAD

**Issue by ajroach42** [spxy/10kbclub#37]
https://ajroach42.com 

Homepage consistently under 10kb. Currently transfers roughly 8.5Kb

Meets noteworthy criteria, 138 points on Floppycast article. 

https://news.ycombinator.com/from?site=ajroach42.com

Thnx.

**Comment by susam** [comment]
Thank you for the submission. This link has been added in commit 70dc961. However, this link is being ignored while publishing the club member list because the compressed transfer size of the home page exceeds 10 KB. Here are the relevant metrics:

```
$ node src/metrics.js https://ajroach42.com/
url: https://ajroach42.com/
htmlSize: 2453
jsonSize: 0
imageSize: 1404
base64Size: 2963
videoSize: 0
cssSize: 22300
jsSize: 0
webfontSize: 0
otherSize: 0
contentSize: 6820
extraSize: 22300
totalSize: 29120

total size: 28.4 KB
content size: 6.7 KB
content ratio: 23%
```

We can see this link being ignored due to large size in the build logs here: https://github.com/susam/10kbclub/actions/runs/3508325212/jobs/5876654482#step:5:18
