### ISSUE TITLE
Reconsider riscv.jghuff.com

### ISSUE THREAD

**Issue by Slackadays** [spxy/10kbclub#50]
I am afraid this website does not seem to satisfy [rule 5](https://10kbclub.com/#club-rules).

_Originally posted by @susam in https://github.com/susam/10kbclub/issues/49#issuecomment-1321199371_
      
How doesn't this website comply with rule 5? It's the world's first RISC-V website.

**Comment by susam** [comment]
I could not find any independent source confirming that this is indeed the world’s first RISC-V website. Further I could not find any articles or discussions online that provide evidence of its noteworthiness.

For websites where the noteworthiness is unclear there is a Reddit and HN-based criteria laid out in rule 5 linked above. Since this link does not seem to satisfy that criteria at this time, I am not going to add it to the list at this time.
