### ISSUE TITLE
Raise the bar to 14kb

### ISSUE THREAD

**Issue by ai-slave** [spxy/10kbclub#54]
**14kb** limit was actually put in place to make the web faster for dial-up users. This was back in the day when people were using 56k modems and things like that. The average website was only about **10kb** back then, so the extra 4kb was to account for images and other things that would make the page load slower.

Nowadays, most people have broadband connections and the average website is much larger than 10kb. So 14kb is actually still a pretty small limit but pays it's homage to the early days of the web.

Inspired by #47

**Comment by susam** [comment]
Thank you for creating this issue. I am not going to be working on this. Raising the bar to 14 KB requires renaming this project as well as getting a new domain name for the project too. This project is going to remain as 10 KB Club. However, this project is released under the MIT License, so anyone who wishes to create a 14 KB club due to the technical merits behind choosing 14 KB as the limit is very welcome to reuse the code from here (if they wish to do so).

**Comment by susam** [comment]
Thank you for creating this issue. Raising the size limit to 14 KB requires renaming this project as well as getting a new domain name in order to be consistent with the new size limit. This project was created for fun as a result of the X KB Club meme in 2020 (1 MB Club, 512 KB Club, 250 Club, etc.) The size limit 10 KB for this project was chosen rather arbitrarily to create yet another list of websites that had even smaller home pages than the other clubs.

For something that is supposed to be only a fun project, I am not going to spend too much time on it. I will be reviewing suggestions to add new websites to the list though and process those requests as soon as I am able to. However, I am not going to spend time changing the size limit used in this project.

Having said that, I must mention that the source code of this project is free and open source. It is available under the terms of the MIT License. So anyone who wishes to create a 14 KB club due to the technical merits for that limit is very welcome to reuse the code from here (if they wish to do so).
