### ISSUE TITLE
lucianmarin.com

### ISSUE THREAD

**Issue by lucianmarin** [spxy/10kbclub#55]
**What is the URL of the website or web application you want to add?**

https://lucianmarin.com/

**What is the total size of data transferred while loading your URL in a web browser? (See [club rules](https://10kbclub.com/#club-rules) > point 1 to figure how to measure the data transfer size.)**

6.1 KB

**Provide a link to a discussion on Reddit or Hacker News where some content from your website received at least 100 upvotes.**

https://news.ycombinator.com/item?id=32445450

https://news.ycombinator.com/item?id=28628011

**Comment by susam** [comment]
When I load the URL https://lucianmarin.com/ in Firefox, I see a compressed transfer size of 42 kB. The bulk of the transfer size is due to `.woff2` files. Here is the metrics report from the metrics script in this project:

```
$ node src/metrics.js https://lucianmarin.com/
url: https://lucianmarin.com/
htmlSize: 1853
jsonSize: 0
imageSize: 0
base64Size: 0
videoSize: 0
cssSize: 896
jsSize: 0
webfontSize: 38227
otherSize: 0
contentSize: 1853
extraSize: 39123
totalSize: 40976

total size: 40.0 KB
content size: 1.8 KB
content ratio: 5%
```

I am afraid I will not be adding this website to the club list at this time due to large transfer size. However, if the compressed transfer size becomes less than 10240 bytes in future, please reopen this ticket and I will add this website to the club list.
